name : CI

on:
# События,которые запускают
push:
 branches: [ "main" ]
pull_request:
 branches: [ "main" ]
jobs:
my_build_job:
runs-on: ubuntu-latest
steps:
uses : actions/checkout@v3
- name: npm install, test and build
run: |
 npm install
 npm run build
- name: Run a one-line script
run: echo Hello, world!
- name: Run a multi-line script
run: | 
 echo Add other actions to build,
 echo test, and deploy yor project.

- name: Run JS file for test
run: node script.js
